routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

Auth::routes();
Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/download', 'MovementController@download')->name('movement.download');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');

    Route::get('refund/download', 'RefundController@download')->name('refund.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');

    Route::post('assembly/partecipate/{assembly_id}/{do}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
});

app/Assembly.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;

use Auth;

class Assembly extends Model
{
    public function users()
    {
        return $this->belongsToMany('App\User')->withPivot('delegate_id')->orderBy('surname', 'asc');
    }

    public function partecipating()
    {
        $user = Auth::user();
        return ($this->users()->where('user_id', $user->id)->count() != 0);
    }

    public function votations()
    {
        return $this->hasMany('App\Votation');
    }

    public function delegations($user)
    {
        $ret = new Collection();
        $ret->push($user);
        $delegating = $this->users()->where('delegate_id', $user->id)->get();
        return $ret->merge($delegating);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Illuminate\Auth\Notifications\ResetPassword as ResetPasswordNotification;

use Log;
use Mail;

use App\Config;

class User extends Authenticatable
{
    use Notifiable;

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function configs()
    {
        return $this->morphMany('App\Config', 'subject');
    }

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function section()
    {
        return $this->belongsTo('App\Section');
    }

    public function fees()
    {
        return $this->hasMany('App\Fee');
    }

    public function getPrintableNameAttribute()
    {
        return sprintf('%s %s', $this->surname, $this->name);
    }

    public function getFullAddressAttribute()
    {
        return sprintf("%s\n%s (%s)", $this->address_street, $this->address_place, $this->address_prov);
    }

    public function getCustomEmailAttribute()
    {
        if (Config::getConfig('custom_email_aliases') == '1') {
            return sprintf('%s@%s', $this->username, Config::getConfig('custom_email_domain'));
        }
        else {
            return null;
        }
    }

    public function getHumanTypeAttribute()
    {
        $types = self::types();

        foreach($types as $t) {
            if ($t->identifier == $this->type)
                return $t->label;
        }

        Log::error('Tipo di utente non riconosciuto: ' . $this->type);
        return '';
    }

    public function getHumanStatusAttribute()
    {
        $statuses = self::statuses();

        foreach($statuses as $s) {
            if ($s->identifier == $this->status)
                return $s->label;
        }

        Log::error('Stato utente non riconosciuto: ' . $this->status);
        return '';
    }

    public function feeAmount()
    {
        static $value = 0;

        if ($value == 0)
            $value = Config::getConfig($this->type . '_annual_fee');

        return $value;
    }

    public function firstMissingFeeYear()
    {
        $this_year = date('Y');

        $last_fee = $this->fees()->orderBy('year', 'desc')->first();
        if ($last_fee) {
            /*
                Qui c'è un errore deliberato, dovrebbe essere
                if ($last_fee->year < $this_year)
                Viene temporaneamente mantenuto così fino al rinnovo dello
                Statuto, sarà da correggere nel prossimo futuro
            */
            if ($last_fee < $this_year)
                return $this_year;
            else
                return $last_fee->year + 1;
        }
        else {
            /*
                I nuovi iscritti (dunque: senza nessuna quota precedente) che si
                iscrivono da ottobre hanno la quota valida per l'anno successivo
            */
            $this_month = date('m');
            if ($this_month < 10) {
                return $this_year;
            }
            else {
                return $this_year + 1;
            }
        }
    }

    public function regularFee()
    {
        return ($this->fees()->where('year', '>=', date('Y'))->first() != null);
    }

    public function hasRole($roles)
    {
        if (is_array($roles) == false) {
            $roles = [$roles];
        }

        foreach($this->roles as $user_role) {
            foreach($roles as $search_role) {
                if ($user_role->name == $search_role) {
                    return true;
                }
            }
        }

        return false;
    }

    public static function types()
    {
        return [
            (object) [
                'identifier' => 'regular',
                'label' => 'Ordinario'
            ],
            (object) [
                'identifier' => 'association',
                'label' => 'Associazione'
            ],
        ];
    }

    public static function statuses()
    {
        return [
            (object) [
                'identifier' => 'pending',
                'label' => 'In Attesa'
            ],
            (object) [
                'identifier' => 'active',
                'label' => 'Attivo'
            ],
            (object) [
                'identifier' => 'suspended',
                'label' => 'Sospeso'
            ],
            (object) [
                'identifier' => 'expelled',
                'label' => 'Espulso'
            ],
            (object) [
                'identifier' => 'dropped',
                'label' => 'Scaduto'
            ],
        ];
    }

    public function sendMail($class)
    {
        $user = $this;

        try {
            $custom = $user->custom_email;
            if (!empty($custom)) {
                Mail::to($user->email)->cc($custom)->send(new $class($user));
            }
            else {
                Mail::to($user->email)->send(new $class($user));
            }
        }
        catch(\Exception $e) {
            Log::error('Impossibile inoltrare mail di notifica a utente ' . $user->id . ': ' . $e->getMessage());
        }
    }

    public function getConfig($name)
    {
        $c = $this->configs()->where('name', $name)->first();
        if (is_null($c))
            return null;
        else
            return $c->value;
    }

    public function setConfig($name, $value)
    {
        $c = $this->configs()->where('name', $name)->first();
        if (is_null($c)) {
            $c = new Config();
            $c->name = $name;
            $c->subject_id = $this->id;
            $c->subject_type = 'App\User';
        }

        $c->value = $value;
        $c->save();
    }

    /******************************************************* CanResetPassword */

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));

        $custom = $this->custom_email;
        if (!empty($custom)) {
            $real_email = $this->email;
            $this->email = $custom;
            $this->notify(new ResetPasswordNotification($token));
            $this->email = $real_email;
        }
    }
}

app/Http/Controllers/AssemblyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Assembly;

class AssemblyController extends EditController
{
    public function __construct()
    {
        parent::init([
            'classname' => 'App\Assembly',
            'view_folder' => 'assembly'
        ]);
    }

    protected function requestToObject($request, $object)
    {
        if ($request->user()->hasRole('admin')) {
            $fields = ['date', 'status', 'announce'];
            $object = $this->fitObject($object, $fields, $request);
        }

        return $object;
    }

    protected function defaultValidations($object)
    {
        return [];
    }

    protected function defaultSortingColumn()
    {
        return 'date';
    }

    public function edit($id)
    {
        return redirect()->route('assembly.index');
    }

    public function partecipate(Request $request, $assembly_id, $do)
    {
        $user = $request->user();
        $assembly = Assembly::find($assembly_id);
        $assembly->users()->detach($user->id);

        foreach($assembly->users()->wherePivot('delegate_id', $user->id)->get() as $delegates) {
            $assembly->users()->detach($delegates->id);
        }

        if ($do != 0) {
            $assembly->users()->attach($user->id);
        }

        return redirect()->route('assembly.index');
    }

    public function delegate(Request $request, $assembly_id, $delegate_id)
    {
        $user = $request->user();
        $assembly = Assembly::find($assembly_id);
        $assembly->users()->detach($user->id);

        if ($delegate_id != 0) {
            $assembly->users()->attach($user->id, ['delegate_id' => $delegate_id]);
        }

        return redirect()->route('assembly.index');
    }
}

resources/views/assembly/form.blade.php
<div class="form-group row">
    <label for="date" class="col-sm-4 col-form-label">Data</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" name="date" value="{{ $object ? $object->date : '' }}">
    </div>
</div>

<div class="form-group row">
    <label for="status" class="col-sm-4 col-form-label">Stato</label>
    <div class="col-sm-8">
        <select class="form-control" name="status" autocomplete="off">
            <option value="pending" {{ $object && $object->status == 'pending' ? 'selected' : '' }}>In Attesa</option>
            <option value="open" {{ $object && $object->status == 'open' ? 'selected' : '' }}>Aperta</option>
            <option value="closed" {{ $object && $object->status == 'closed' ? 'selected' : '' }}>Chiusa</option>
        </select>
    </div>
</div>

<div class="form-group row">
    <label for="announce" class="col-sm-4 col-form-label">Convocazione</label>
    <div class="col-sm-8">
        <textarea class="form-control" name="announce" rows="10">{{ $object ? $object->announce : '' }}</textarea>
    </div>
</div>

resources/views/assembly/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @can('create', App\Assembly::class)
        <div class="row">
            <div class="col-md-12">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createAssembly">Registra Nuova</button>
                <div class="modal fade" id="createAssembly" tabindex="-1" role="dialog">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Convoca Assemblea</h5>
                                <button type="button" class="close" data-dismiss="modal">
                                    <span>&times;</span>
                                </button>
                            </div>
                            <form method="POST" action="{{ route('assembly.store') }}">
                                @csrf
                                <div class="modal-body">
                                    @include('assembly.form', ['object' => null])
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                                    <button type="submit" class="btn btn-primary">Salva</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endif

    <div class="row mt-3">
        <div class="col-md-12">
            <div class="accordion" id="assemblies_list">
                @foreach($objects as $assembly)
                    <div class="card">
                        <div class="card-header" id="head_assembly_{{ $assembly->id }}">
                            <h2 class="mb-0">
                                <button class="btn btn-link {{ $assembly->status != 'open' ? 'collapsed' : '' }}" type="button" data-toggle="collapse" data-target="#assembly_{{ $assembly->id }}">
                                    {{ printableDate($assembly->date) }}
                                </button>
                            </h2>
                        </div>
                        <div id="assembly_{{ $assembly->id }}" class="collapse {{ $assembly->status == 'open' ? 'show' : '' }}" data-parent="#assemblies_list">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        @include('assembly.votations', ['assembly' => $assembly])

                                        @can('update', $assembly)
                                            <form method="POST" action="{{ route('assembly.update', $assembly->id) }}">
                                                @method('PUT')
                                                @csrf

                                                @include('assembly.form', ['object' => $assembly])

                                                <div class="form-group row">
                                                    <div class="col-sm-10">
                                                        <button type="submit" class="btn btn-primary">Salva</button>
                                                    </div>
                                                </div>
                                            </form>

                                            <hr>

                                            @include('assembly.managevotations', ['assembly' => $assembly])
                                        @else
                                            <p>
                                                {!! nl2br($assembly->announce) !!}
                                            </p>
                                        @endif
                                    </div>
                                    <div class="col-md-6">
                                        <?php $actually_partecipating = $assembly->partecipating() ?>

                                        @if($assembly->status == 'open')
                                            <div class="row mb-3">
                                                <div class="col-md-12">
                                                    @if($actually_partecipating)
                                                        <form method="POST" action="{{ route('assembly.partecipate', ['assembly_id' => $assembly->id, 'do' => 0]) }}">
                                                            @csrf
                                                            <button type="submit" class="btn btn-primary">Revoca Partecipazione</button>
                                                        </form>
                                                    @else
                                                        <form method="POST" action="{{ route('assembly.partecipate', ['assembly_id' => $assembly->id, 'do' => 1]) }}">
                                                            @csrf
                                                            <button type="submit" class="btn btn-primary">Segnala Partecipazione</button>
                                                        </form>
                                                    @endif
                                                </div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-12">
                                                    <ul class="list-group">
                                                        @foreach($assembly->users as $partecipant)
                                                            <li class="list-group-item">
                                                                {{ $partecipant->printable_name }}

                                                                @if($actually_partecipating == false && $partecipant->pivot->delegate_id == 0 && $assembly->users()->wherePivot('delegate_id', $partecipant->id)->count() < 3)
                                                                    <form method="POST" action="{{ route('assembly.delegate', ['assembly_id' => $assembly->id, 'delegate_id' => $partecipant->id]) }}" class="float-right">
                                                                        @csrf
                                                                        <button type="submit" class="btn">Delega</button>
                                                                    </form>
                                                                @elseif($partecipant->pivot->delegate_id != 0)
                                                                    {{ $partecipant->pivot->delegate_id != 0 ? '(ha delegato ' . App\User::find($partecipant->pivot->delegate_id)->printable_name . ')' : '' }}
                                                                @endif
                                                            </li>
                                                        @endforeach
                                                    </ul>
                                                </div>
                                            </div>
                                        @else
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <ul class="list-group">
                                                        @foreach($assembly->users as $partecipant)
                                                            <li class="list-group-item">{{ $partecipant->printable_name }} {{ $partecipant->pivot->delegate_id != 0 ? '(ha delegato ' . App\User::find($partecipant->pivot->delegate_id)->printable_name . ')' : '' }}</li>
                                                        @endforeach
                                                    </ul>
                                                </div>
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/assembly/managevotations.blade.php
@if($assembly->status != 'closed')
    @foreach($assembly->votations as $votation)
        <p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editVotation{{ $votation->id }}">Edita Votazione: {{ substr($votation->question, 0, 20) }}...</button>
        </p>

        <div class="modal fade" id="editVotation{{ $votation->id }}" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modifica Votazione</h5>
                        <button type="button" class="close" data-dismiss="modal">
                            <span>&times;</span>
                        </button>
                    </div>
                    <form method="POST" action="{{ route('votation.update', $votation->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="modal-body">
                            @include('votation.form', ['object' => $votation])
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                            <button type="submit" class="btn btn-primary">Salva</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endforeach

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createVotation">Nuova Votazione</button>
    <div class="modal fade" id="createVotation" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Nuova Votazione</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <form method="POST" action="{{ route('votation.store') }}">
                    @csrf
                    <div class="modal-body">
                        @include('votation.form', ['object' => null, 'assembly_id' => $assembly->id])
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                        <button type="submit" class="btn btn-primary">Salva</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endif

resources/views/assembly/votations.blade.php
<?php $runnings = $assembly->votations()->where('status', 'running')->get() ?>
@if($runnings->isEmpty() == false)
    @foreach($runnings as $running_votation)
        @if($running_votation->hasVoted($currentuser))
            <p class="alert alert-info">
                Hai già votato per la votazione in corso. In attesa dei risultati.<br>
                Sono stati espressi {{ $running_votation->votes()->count() }} voti.
            </p>
        @else
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#runningVotation{{ $running_votation->id }}">Votazione in corso! Clicca qui!</button>
            <div class="modal fade" id="runningVotation{{ $running_votation->id }}" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Votazione in Corso</h5>
                            <button type="button" class="close" data-dismiss="modal">
                                <span>&times;</span>
                            </button>
                        </div>
                        <form method="POST" action="{{ route('vote.store') }}">
                            @csrf
                            <div class="modal-body">
                                @include('vote.form', ['votation' => $running_votation])
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                                <button type="submit" class="btn btn-primary">Salva</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        @endif
    @endforeach

    <hr>
@endif

<?php $closed_votations = $assembly->votations()->where('status', 'closed')->get() ?>
@if($closed_votations->isEmpty() == false)
    @foreach($closed_votations as $closed_votation)
        <p>
            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#closedVotation{{ $closed_votation->id }}">Esito Votazione: {{ substr($closed_votation->question, 0, 20) }}...</button>
        </p>

        <div class="modal fade" id="closedVotation{{ $closed_votation->id }}" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Votazione Conclusa</h5>
                        <button type="button" class="close" data-dismiss="modal">
                            <span>&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @include('votation.result', ['votation' => $closed_votation])
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                    </div>
                </div>
            </div>
        </div>
    @endforeach

    <hr>
@endif