routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

Auth::routes();
Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/download', 'MovementController@download')->name('movement.download');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');

    Route::get('refund/download', 'RefundController@download')->name('refund.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');

    Route::post('assembly/partecipate/{assembly_id}/{do}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
});

app/AccountRow.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AccountRow extends Model
{
    public function movement()
    {
        return $this->belongsTo('App\Movement');
    }

    public function account()
    {
        return $this->belongsTo('App\Account');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function section()
    {
        return $this->belongsTo('App\Section');
    }

    public function getAmountAttribute()
    {
        return $this->amount_in - $this->amount_out;
    }

    /*
        Questa funzione genera una stringa che sia poi leggibile da
        getFeeYear(). Permette di identificare i movimenti che sono stati a
        priori identificati come pagamenti di quote di iscrizione, per poi
        appunto poterle registrare in quanto quote.
    */
    public static function createFeeNote($user, $year)
    {
        return sprintf('Saldo quota %s %s', $year, $user->printable_name);
    }

    public static function createDonationNote($name)
    {
        return sprintf('Donazione per %s', $name);
    }

    public function getFeeYear()
    {
        return preg_replace('/^Saldo quota ([0-9]{4}) .*$/', '\1', $this->notes);
    }

    public function getPrintableAmountAttribute()
    {
        if (!empty($this->amount_in) && $this->amount_in != 0) {
            return $this->amount_in;
        }
        else {
            return ($this->amount_out * -1);
        }
    }
}

app/Bank.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    public function movements()
    {
        return $this->hasMany('App\Movement');
    }

    public function rules()
    {
        return $this->hasMany('App\AccountRule');
    }

    public static function types()
    {
        return [
            (object) [
                'identifier' => 'paypal',
                'label' => 'PayPal'
            ],
            (object) [
                'identifier' => 'unicredit',
                'label' => 'Unicredit Banca'
            ],
        ];
    }

    public function getLastUpdateAttribute()
    {
        /*
            In fase di importazione degli estratti conto PayPal creo un
            movimento per tenere traccia delle commissioni, che però non deve
            essere considerato come ultimo movimento
        */
        if ($this->type == 'paypal') {
            return $this->movements()->where('notes', '!=', 'Commissioni PayPal')->max('date');
        }
        else {
            return $this->movements()->max('date');
        }
    }
}

app/Movement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;

use App\AccountRow;
use App\Config;

class Movement extends Model
{
    public function bank()
    {
        return $this->belongsTo('App\Bank');
    }

    public function account_rows()
    {
        return $this->hasMany('App\AccountRow');
    }

    public function receipt()
    {
        return $this->hasOne('App\Receipt');
    }

    public function refund()
    {
        return $this->hasMany('App\Refund');
    }

    public function getAttachmentsPathAttribute()
    {
        return storage_path('accounting/' . $this->id);
    }

    public function getAttachmentsAttribute()
    {
        $ret = new Collection();

        $path = $this->attachments_path;
        if (file_exists($path)) {
            $files = scandir($path);

            foreach($files as $f) {
                if ($f[0] == '.')
                    continue;

                $ret->push($f);
            }
        }

        return $ret;
    }

    public function alreadyTracked()
    {
        return (Movement::where('date', $this->date)->where('amount', $this->amount)->where('identifier', $this->identifier)->where('notes', $this->notes)->count() != 0);
    }

    public function attachFile($file)
    {
        $file->move($this->attachments_path, $file->getClientOriginalName());
    }

    public function getFeePayments($user)
    {
        $ret = new Collection();

        if (is_object($user) == false) {
            $user_id = $user;
            $user = User::find($user_id);
            if (is_null($user)) {
                Log::error('Errore nel riconoscimento utente di cui generare le quote di iscrizione: ' . $user_id);
                return $ret;
            }
        }

        $fees_account = Config::feesAccount();
        $donations_account = Account::where('donations', true)->first();

        $amount = $this->amount;
        $year = $user->firstMissingFeeYear();
        $guessed = true;

        while($amount >= $user->feeAmount()) {
            $ar = new AccountRow();
            $ar->movement_id = $this->id;
            $ar->account_id = $fees_account->id;
            $ar->amount_in = $user->feeAmount();
            $ar->user_id = $user->id;
            $ar->notes = AccountRow::createFeeNote($user, $year);
            $ret->push($ar);

            $amount -= $user->feeAmount();
            $year++;
        }

        if ($amount != 0) {
            $ar = new AccountRow();
            $ar->movement_id = $this->id;
            $ar->account_id = $donations_account->id;
            $ar->amount_in = $amount;
            $ar->notes = sprintf('Donazione da parte di %s', $user->printable_name);
            $ret->push($ar);
        }

        return $ret;
    }

    public function getAccountRowFromHistory($guess_by_note)
    {
        $prev_movement = Movement::where('notes', 'like', $guess_by_note)->has('account_rows')->orderBy('id', 'desc')->first();

        if ($prev_movement) {
            $prev_account_row = $prev_movement->account_rows()->first();
            if ($prev_account_row) {
                $ar = new AccountRow();
                $ar->movement_id = $this->id;
                $ar->account_id = $prev_account_row->account_id;
                $ar->user_id = $prev_account_row->user_id;
                $ar->section_id = $prev_account_row->section_id;
                $ar->notes = $prev_account_row->notes;

                if ($this->amount > 0)
                    $ar->amount_in = abs($this->amount);
                else
                    $ar->amount_out = abs($this->amount);

                return $ar;
            }
        }

        return null;
    }

    private function guessByRules()
    {
        foreach($this->bank->rules as $rule) {
            if (preg_match($rule->fixed_rule, $this->notes)) {
                $ar = new AccountRow();
                $ar->movement_id = $this->id;
                $ar->account_id = $rule->account_id;
                $ar->notes = $rule->notes;

                if ($this->amount > 0)
                    $ar->amount_in = abs($this->amount);
                else
                    $ar->amount_out = abs($this->amount);

                $ret = new Collection();
                $ret->push($ar);
                return $ret;
            }
        }

        return null;
    }

    public function guessRows()
    {
        $ret = $this->guessByRules();
        $guessed = false;

        if ($ret) {
            $guessed = true;
        }
        else {
            $ret = new Collection();

            if ($this->bank->type == 'paypal') {
                list($name, $email, $causal) = explode(' - ', $this->notes);
                $name = str_replace("'", "\'", $name);

                $user = User::whereRaw("CONCAT(name, ' ', surname) = '$name'")->first();
                if (!is_null($user) && $this->amount >= $user->feeAmount()) {
                    $ret = $this->getFeePayments($user);
                    $guessed = true;
                }
                else {
                    $guess_note = sprintf('%s - %s - %%', $name, $email);
                    $ar = $this->getAccountRowFromHistory($guess_note);
                    if ($ar) {
                        $ret->push($ar);
                        $guessed = true;
                    }
                }
            }
            else if ($this->bank->type == 'unicredit') {
                $name = trim(preg_replace('/^BONIFICO A VOSTRO FAVORE BONIFICO SEPA DA ([A-Z ]*) PER .*$/', '\1', $this->notes));
                $user = User::whereRaw("CONCAT(surname, ' ', name) = '$name'")->first();
                if (!is_null($user) && $this->amount >= $user->feeAmount()) {
                    $ret = $this->getFeePayments($user);
                    $guessed = true;
                }
                else {
                    $ar = $this->getAccountRowFromHistory($this->notes);
                    if ($ar) {
                        $ret->push($ar);
                        $guessed = true;
                    }
                }
            }
        }

        if ($guessed == false) {
            $ar = new AccountRow();

            if ($this->amount > 0)
                $ar->amount_in = abs($this->amount);
            else
                $ar->amount_out = abs($this->amount);

            $ret->push($ar);
        }

        return $ret;
    }

    public function generateReceipt()
    {
        $causals = [];
        $headers = [];

        if ($this->amount <= 0) {
            return;
        }

        foreach($this->account_rows as $ar) {
            if ($ar->user) {
                $headers[] = $ar->user->full_address;
            }

            $causals[] = trim($ar->notes);
        }

        $receipt = $this->receipt;

        if (is_null($receipt)) {
            $receipt = new Receipt();
            $receipt->movement_id = $this->id;
        }

        $receipt->date = date('Y-m-d');
        $receipt->header = join("\n", $headers);
        $receipt->causal = join("\n", $causals);
        $receipt->save();
    }
}

app/Receipt.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use PDF;

class Receipt extends Model
{
    public function movement()
    {
        return $this->belongsTo('App\Movement');
    }

    public function getFullNumberAttribute()
    {
        list($year, $month, $day) = explode('-', $this->date);
        return sprintf('%s/%s', $this->number, $year);
    }

    public function getLinkAttribute()
    {
        return route('receipt.show', $this->id);
    }

    public function getPathAttribute()
    {
        $filename = sprintf('%s.pdf', str_replace('/', '_', $this->full_number));
        return storage_path('receipts/' . $filename);
    }

    public function generate()
    {
        $pdf = PDF::loadView('receipt.pdf', ['object' => $this]);
        $pdf->save($this->path);
    }
}

app/Refund.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;

class Refund extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function section()
    {
        return $this->belongsTo('App\Section');
    }

    public function movement()
    {
        return $this->belongsTo('App\Movement');
    }

    public function getPrintableDescriptionAttribute()
    {
        return sprintf('%s € - %s - %s', $this->amount, $this->user ? $this->user->printable_name : '?', $this->section ? 'Sezione Locale di ' . $this->section->city : 'Nessuna Sezione Locale');
    }

    public function getAttachmentsPathAttribute()
    {
        return storage_path('refunds/' . $this->id);
    }

    public function getAttachmentsAttribute()
    {
        $ret = new Collection();

        $path = $this->attachments_path;
        if (file_exists($path)) {
            $files = scandir($path);

            foreach($files as $f) {
                if ($f[0] == '.')
                    continue;

                $ret->push($f);
            }
        }

        return $ret;
    }

    public function attachFile($file)
    {
        $file->move($this->attachments_path, $file->getClientOriginalName());
    }
}

resources/views/movement/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p>
                Movimento {{ $movement->identifier }} su banca {{ $movement->bank->name }}
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <form method="POST" action="{{ route('movement.update', 0) }}">
                @method('PUT')
                @csrf

                @include('movement.editblock', ['movement' => $movement])

                <br>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Salva</button>
                    </div>
                </div>
            </form>

            <div class="card mt-3">
                <div class="card-header">Allegati</div>

                <div class="card-body">
                    <ul>
                        @foreach($movement->attachments as $attach)
                            <li><a href="{{ route('movement.download', ['file' => $movement->id . '/' . $attach]) }}">{{ basename($attach) }}</a></li>
                        @endforeach
                    </ul>

                    <form method="POST" action="{{ route('movement.attach', $movement->id) }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <div class="col-sm-4">
                                <input type="file" class="form-control" name="file">
                            </div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-primary">Allega File</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            @if($movement->amount > 0)
                <div class="card mt-3">
                    <div class="card-header">Ricevuta</div>

                    <div class="card-body">
                        @if($movement->receipt)
                            <a class="btn btn-default" href="{{ $movement->receipt->link }}">Scarica Ricevuta {{ $movement->receipt->full_number }}</a>
                        @else
                            <form method="POST" action="{{ route('receipt.store') }}">
                                @csrf

                                <input type="hidden" name="movement_id" value="{{ $movement->id }}">

                                <div class="form-group row">
                                    <label for="date" class="col-sm-4 col-form-label">Data</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control" name="date" value="{{ date('Y-m-d') }}">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="header" class="col-sm-4 col-form-label">Intestazione</label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control" name="header"></textarea>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="causal" class="col-sm-4 col-form-label">Causale</label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control" name="causal"></textarea>
                                    </div>
                                </div>

                                @if($movement->amount >= 77.47)
                                    <div class="form-group row">
                                        <label for="stamp" class="col-sm-4 col-form-label">Marca da Bollo</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="stamp">
                                        </div>
                                    </div>
                                @endif

                                <hr>
                                <div class="form-group row">
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Genera Ricevuta</button>
                                    </div>
                                </div>
                            </form>
                        @endif
                    </div>
                </div>
            @else
                <div class="card mt-3">
                    <div class="card-header">Rimborsi Spese</div>

                    <div class="card-body">
                        @if($movement->refund->isEmpty() == false)
                            <ul>
                                @foreach($movement->refund as $r)
                                    <li><a href="{{ route('refund.edit', $r->id) }}">{{ $r->printable_description }}</a></li>
                                @endforeach
                            </ul>
                        @else
                            <?php $pendings = App\Refund::where('refunded', false)->whereDoesntHave('movement')->get() ?>

                            @if($pendings->isEmpty())
                                <div class="alert alert-info">
                                    Non ci sono rimborsi spese in attesa.
                                </div>
                            @else
                                <form method="POST" action="{{ route('movement.refund', $movement->id) }}">
                                    @csrf

                                    <fieldset class="form-group">
                                        <div class="row">
                                            <legend class="col-form-label col-sm-4 pt-0">Rimborsi in Attesa</legend>
                                            <div class="col-sm-8">
                                                @foreach($pendings as $p)
                                                    <div class="form-check">
                                                        <input class="form-check-input" type="checkbox" name="refund_id[]" value="{{ $p->id }}">
                                                        <label class="form-check-label">
                                                            {{ $p->printable_description }}
                                                        </label>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </fieldset>

                                    <div class="form-group row">
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-primary">Rimborsa</button>
                                        </div>
                                    </div>
                                </form>
                            @endif
                        @endif
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/movement/editblock.blade.php
<ul class="list-group">
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-3">
                {{ $movement->date }}
            </div>
            <div class="col-md-3">
                {{ $movement->amount }}
            </div>
            <div class="col-md-6">
                {{ $movement->notes }}
            </div>
        </div>
    </li>

    @if($movement->account_rows->isEmpty() == false)
        @foreach($movement->account_rows as $ar)
            @include('accountrow.editblock', ['ar' => $ar])
        @endforeach
    @elseif(($guessed = $movement->guessRows())->isEmpty() == false)
        @foreach($guessed as $ar)
            @include('accountrow.editblock', ['ar' => $ar])
        @endforeach
    @else
        @include('accountrow.editblock', ['ar' => null])
    @endif

    <li class="list-group-item">
        <div class="form-check float-right">
            <input class="form-check-input" type="checkbox" name="remove[]" value="{{ $movement->id }}" id="remove{{ $movement->id }}">
            <label class="form-check-label" for="remove{{ $movement->id }}">
                Elimina
            </label>
        </div>
        <button class="btn btn-default btn-sm add-row"><span class="oi oi-plus"></span></button>
        <ul class="hidden">
            @include('accountrow.editblock', ['ar' => null])
        </ul>
    </li>
</ul>

resources/views/movement/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form class="form-inline" method="POST" action="{{ route('movement.store') }}" enctype="multipart/form-data">
                @csrf

                @foreach(App\Bank::orderBy('name')->get() as $bank)
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" id="bank_{{ $bank->id }}" type="radio" name="bank_id" value="{{ $bank->id }}" required>
                        <label class="form-check-label" for="bank_{{ $bank->id }}">{{ $bank->name }} (ultimo aggiornamento: {{ $bank->last_update }})</label>
                    </div>
                @endforeach

                <div class="form-group">
                    <input type="file" class="form-control" name="file">
                </div>

                <button type="submit" class="btn btn-primary">Importa Nuovi Movimenti</button>
            </form>
        </div>
        <div class="col-md-3">
            @if(App\Movement::whereDoesntHave('account_rows')->count() != 0)
                <a href="{{ route('movement.review') }}" class="btn btn-primary float-right">{{ App\Movement::whereDoesntHave('account_rows')->count() }} Movimenti da Revisionare</a>
            @endif
        </div>
    </div>

    <hr>

    <nav class="nav mt-3">
        @foreach(App\Movement::selectRaw('YEAR(date) as year')->distinct()->orderBy('year', 'asc')->pluck('year') as $nav_year)
            <a class="nav-link {{ $year == $nav_year ? 'active' : '' }}" href="{{ route('movement.index', ['year' => $nav_year]) }}">{{ $nav_year }}</a>
        @endforeach
    </nav>

    <div class="row mt-3">
        <div class="col-md-12">
            <ul class="list-group">
                <?php

                function collectByAccount($account, $year) {
                    $row = (object)[
                        'name' => $account->name,
                        'in' => 0,
                        'out' => 0,
                        'sum' => 0,
                        'children' => []
                    ];

                    $row->in = App\AccountRow::where('account_id', $account->id)->whereHas('movement', function($query) use ($year) {
                        $query->whereRaw("YEAR(date) = $year");
                    })->sum('amount_in');

                    $row->out = App\AccountRow::where('account_id', $account->id)->whereHas('movement', function($query) use ($year) {
                        $query->whereRaw("YEAR(date) = $year");
                    })->sum('amount_out');

                    $row->sum = $row->in - $row->out;

                    foreach($account->children as $child) {
                        $c = collectByAccount($child, $year);
                        if ($c->sum != 0) {
                            $row->children[] = $c;
                            $row->in += $c->in;
                            $row->out += $c->out;
                            $row->sum += $c->sum;
                        }
                    }

                    return $row;
                }

                function displayByAccount($row, $deep) {
                    echo sprintf('<li class="list-group-item">
                        <div class="row">
                            <div class="col-md-%s offset-md-%s">%s</div>

                            <div class="col-md-2">
                                <span class="float-right badge badge-success">%s €</span>
                            </div>
                            <div class="col-md-2">
                                <span class="float-right badge badge-danger">%s €</span>
                            </div>
                            <div class="col-md-2">
                                <span class="float-right">%s €</span>
                            </div>
                        </div>
                    </li>', 6 - $deep, $deep, $row->name, sprintf('%.02f', $row->in), sprintf('%.02f', $row->out), sprintf('%.02f', $row->sum));

                    foreach($row->children as $child) {
                        displayByAccount($child, $deep + 1);
                    }
                }

                $total_in = 0;
                $total_out = 0;
                $total_sum = 0;

                foreach(App\Account::whereNull('parent_id')->orderBy('name', 'asc')->get() as $account) {
                    $row = collectByAccount($account, $year);
                    displayByAccount($row, 0);
                    $total_in += $row->in;
                    $total_out += $row->out;
                    $total_sum += $row->sum;
                }

                ?>

                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-6"><strong>Totale</strong></div>

                        <div class="col-md-2">
                            <span class="float-right badge badge-success"><strong>{{ sprintf('%.02f', $total_in) }} €</strong></span>
                        </div>
                        <div class="col-md-2">
                            <span class="float-right badge badge-danger"><strong>{{ sprintf('%.02f', $total_out) }} €</strong></span>
                        </div>
                        <div class="col-md-2">
                            <span class="float-right"><strong>{{ sprintf('%.02f', $total_sum) }} €</strong></span>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Data</th>
                        <th>Valore</th>
                        <th>Account</th>
                        <th>Note</th>
                        <th>Visualizza</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($objects as $row)
                        <tr class="{{ $row->amount_in > 0 ? 'table-success' : 'table-danger' }}">
                            <td>{{ $row->movement->date }}</td>
                            <td>{{ $row->printable_amount }}</td>
                            <td>{{ $row->account ? $row->account->printable_name : '???' }}</td>
                            <td>{{ $row->notes }}</td>
                            <td><a href="{{ route('movement.edit', $row->movement->id) }}"><span class="oi oi-pencil"></span></a></td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/movement/review.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p>
                I movimenti marcati come "Quote Associative" sono automaticamente elaborati per estrapolare più quote pagate insieme per l'utente selezionato. L'eventuale disavanzo viene contato come "Donazione".
            </p>
            <p>
                Correggere manualmente i movimenti legati a fatture dei fornitori, nella causale specifica il numero di fattura e magari la motivazione.
            </p>
        </div>
    </div>

    @if($pendings->isEmpty() == false)
        <div class="row">
            <div class="col-md-12">
                <form method="POST" action="{{ route('movement.update', 0) }}">
                    @method('PUT')
                    @csrf

                    @foreach($pendings as $movement)
                        @include('movement.editblock', ['movement' => $movement])
                        <br>
                    @endforeach

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Salva</button>
                        </div>
                    </div>
                </form>

                {!! $pendings->links() !!}
            </div>
        </div>
    @endif
</div>
@endsection