routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

Auth::routes();
Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/download', 'MovementController@download')->name('movement.download');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');

    Route::get('refund/download', 'RefundController@download')->name('refund.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');

    Route::post('assembly/partecipate/{assembly_id}/{do}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
});

app/Refund.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;

class Refund extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function section()
    {
        return $this->belongsTo('App\Section');
    }

    public function movement()
    {
        return $this->belongsTo('App\Movement');
    }

    public function getPrintableDescriptionAttribute()
    {
        return sprintf('%s € - %s - %s', $this->amount, $this->user ? $this->user->printable_name : '?', $this->section ? 'Sezione Locale di ' . $this->section->city : 'Nessuna Sezione Locale');
    }

    public function getAttachmentsPathAttribute()
    {
        return storage_path('refunds/' . $this->id);
    }

    public function getAttachmentsAttribute()
    {
        $ret = new Collection();

        $path = $this->attachments_path;
        if (file_exists($path)) {
            $files = scandir($path);

            foreach($files as $f) {
                if ($f[0] == '.')
                    continue;

                $ret->push($f);
            }
        }

        return $ret;
    }

    public function attachFile($file)
    {
        $file->move($this->attachments_path, $file->getClientOriginalName());
    }
}

app/Http/Controllers/RefundController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;

use App\Refund;

class RefundController extends EditController
{
    public function __construct()
    {
        parent::init([
            'classname' => 'App\Refund',
            'view_folder' => 'refund'
        ]);
    }

    protected function query($query, $id = null)
    {
        $user = Auth::user();

        if ($user->hasRole('admin') == false) {
            $query->where('user_id', $user->id);
        }

        return $query;
    }

    protected function requestToObject($request, $object)
    {
        $object->date = $request->input('date');
        $object->amount = $request->input('amount');
        $object->section_id = $request->input('section_id', 0);
        $object->notes = $request->input('notes');

        if ($request->user()->hasRole('admin')) {
            $object->refunded = $request->has('refunded');
            $object->user_id = $request->input('user_id', 0);
        }
        else {
            $object->user_id = $request->user()->id;
        }

        return $object;
    }

    protected function defaultValidations($object)
    {
        return [
            'amount' => 'required|numeric',
            'notes' => 'required',
        ];
    }

    protected function defaultSortingColumn()
    {
        return 'date';
    }

    protected function afterSaving($request, $object)
    {
        if ($request->hasFile('file')) {
            $files = $request->file('file');

            foreach($files as $f) {
                $object->attachFile($f);
            }
        }
    }

    public function download(Request $request)
    {
        return response()->download(storage_path('refunds/' . $request->input('file')));
    }
}

resources/views/refund/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form method="POST" action="{{ route('refund.update', $object->id) }}" enctype="multipart/form-data">
                @method('PUT')
                @csrf

                @include('refund.form', ['object' => $object])

                @if($currentuser->hasRole('admin'))
                    <div class="form-group row">
                        <label for="section_id" class="col-sm-4 col-form-label">Rimborsato</label>
                        <div class="col-sm-8">
                            <div class="btn-group-toggle" data-toggle="buttons">
                                <label class="btn btn-success {{ $object->refunded ? 'active' : '' }}">
                                    <input type="checkbox" name="refunded" {{ $object->refunded ? 'checked' : '' }} autocomplete="off"> Rimborsato
                                </label>
                            </div>
                        </div>
                    </div>
                @endif

                <hr>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Salva</button>
                    </div>
                </div>
            </form>

            <br>

            @can('delete', $object)
                <form method="POST" action="{{ route('refund.destroy', $object->id) }}">
                    @method('DELETE')
                    @csrf

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-danger">Elimina Richiesta di Rimborso Spese</button>
                        </div>
                    </div>
                </form>
            @endcan
        </div>
    </div>
</div>
@endsection

resources/views/refund/form.blade.php
<div class="form-group row">
    <label for="date" class="col-sm-4 col-form-label">Data</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" name="date" value="{{ $object ? $object->date : date('Y-m-d') }}" required>
    </div>
</div>
<div class="form-group row">
    <label for="amount" class="col-sm-4 col-form-label">Ammontare</label>
    <div class="col-sm-8">
        <input type="number" class="form-control" step="0.01" name="amount" value="{{ $object ? $object->amount : '' }}" required>
    </div>
</div>
@if($currentuser->hasRole('admin'))
    <div class="form-group row">
        <label for="user_id" class="col-sm-4 col-form-label">Utente</label>
        <div class="col-sm-8">
            @include('user.select', ['name' => 'user_id', 'select' => ($object ? $object->user_id : $currentuser->id)])
        </div>
    </div>
@endif
<div class="form-group row">
    <label for="section_id" class="col-sm-4 col-form-label">Sezione Locale</label>
    <div class="col-sm-8">
        @include('section.select', ['name' => 'section_id', 'select' => ($object ? $object->section_id : 0)])
    </div>
</div>
<div class="form-group row multiple-files">
    <label for="file" class="col-sm-4 col-form-label">Files</label>
    <div class="col-sm-8">
        @if($object)
            <ul>
                @foreach($object->attachments as $attach)
                    <li><a href="{{ route('refund.download', ['file' => $object->id . '/' . $attach]) }}">{{ basename($attach) }}</a></li>
                @endforeach
            </ul>
        @endif

        <input type="file" name="file[]" autocomplete="off" {{ $object ? '' : 'required' }}>
        <small class="form-text text-muted">Si prega di allegare tutta la documentazione correlata: fatture, scontrini, biglietti...</small>
    </div>
</div>
<div class="form-group row">
    <label for="notes" class="col-sm-4 col-form-label">Note</label>
    <div class="col-sm-8">
        <textarea class="form-control" name="notes" placeholder="Scrivere qui una breve descrizione delle spese affrontate" required>{{ $object ? $object->notes : '' }}</textarea>
    </div>
</div>

resources/views/refund/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createUser">Nuovo Rimborso Spese</button>
            <div class="modal fade" id="createUser" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Nuovo Rimborso Spese</h5>
                            <button type="button" class="close" data-dismiss="modal">
                                <span>&times;</span>
                            </button>
                        </div>
                        <form method="POST" action="{{ route('refund.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="modal-body">
                                @include('refund.form', ['object' => null])
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                                <button type="submit" class="btn btn-primary">Salva</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Data</th>
                        <th>Ammontare</th>
                        <th>Socio</th>
                        <th>Sezione</th>
                        <th>Dettagli</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($objects as $refund)
                        <tr class="{{ $refund->refunded ? 'table-success' : 'table-danger' }}">
                            <td>{{ $refund->date }}</td>
                            <td>{{ $refund->amount }}</td>
                            <td>{{ $refund->user ? $refund->user->printable_name : '' }}</td>
                            <td>{{ $refund->section ? $refund->section->city : '' }}</td>
                            <td>
                                <a href="{{ route('refund.edit', $refund->id) }}"><span class="oi oi-pencil"></span></a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection