routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

Auth::routes();
Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/download', 'MovementController@download')->name('movement.download');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');

    Route::get('refund/download', 'RefundController@download')->name('refund.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');

    Route::post('assembly/partecipate/{assembly_id}/{do}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
});

app/Receipt.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use PDF;

class Receipt extends Model
{
    public function movement()
    {
        return $this->belongsTo('App\Movement');
    }

    public function getFullNumberAttribute()
    {
        list($year, $month, $day) = explode('-', $this->date);
        return sprintf('%s/%s', $this->number, $year);
    }

    public function getLinkAttribute()
    {
        return route('receipt.show', $this->id);
    }

    public function getPathAttribute()
    {
        $filename = sprintf('%s.pdf', str_replace('/', '_', $this->full_number));
        return storage_path('receipts/' . $filename);
    }

    public function generate()
    {
        $pdf = PDF::loadView('receipt.pdf', ['object' => $this]);
        $pdf->save($this->path);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Illuminate\Auth\Notifications\ResetPassword as ResetPasswordNotification;

use Log;
use Mail;

use App\Config;

class User extends Authenticatable
{
    use Notifiable;

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function configs()
    {
        return $this->morphMany('App\Config', 'subject');
    }

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function section()
    {
        return $this->belongsTo('App\Section');
    }

    public function fees()
    {
        return $this->hasMany('App\Fee');
    }

    public function getPrintableNameAttribute()
    {
        return sprintf('%s %s', $this->surname, $this->name);
    }

    public function getFullAddressAttribute()
    {
        return sprintf("%s\n%s (%s)", $this->address_street, $this->address_place, $this->address_prov);
    }

    public function getCustomEmailAttribute()
    {
        if (Config::getConfig('custom_email_aliases') == '1') {
            return sprintf('%s@%s', $this->username, Config::getConfig('custom_email_domain'));
        }
        else {
            return null;
        }
    }

    public function getHumanTypeAttribute()
    {
        $types = self::types();

        foreach($types as $t) {
            if ($t->identifier == $this->type)
                return $t->label;
        }

        Log::error('Tipo di utente non riconosciuto: ' . $this->type);
        return '';
    }

    public function getHumanStatusAttribute()
    {
        $statuses = self::statuses();

        foreach($statuses as $s) {
            if ($s->identifier == $this->status)
                return $s->label;
        }

        Log::error('Stato utente non riconosciuto: ' . $this->status);
        return '';
    }

    public function feeAmount()
    {
        static $value = 0;

        if ($value == 0)
            $value = Config::getConfig($this->type . '_annual_fee');

        return $value;
    }

    public function firstMissingFeeYear()
    {
        $this_year = date('Y');

        $last_fee = $this->fees()->orderBy('year', 'desc')->first();
        if ($last_fee) {
            /*
                Qui c'è un errore deliberato, dovrebbe essere
                if ($last_fee->year < $this_year)
                Viene temporaneamente mantenuto così fino al rinnovo dello
                Statuto, sarà da correggere nel prossimo futuro
            */
            if ($last_fee < $this_year)
                return $this_year;
            else
                return $last_fee->year + 1;
        }
        else {
            /*
                I nuovi iscritti (dunque: senza nessuna quota precedente) che si
                iscrivono da ottobre hanno la quota valida per l'anno successivo
            */
            $this_month = date('m');
            if ($this_month < 10) {
                return $this_year;
            }
            else {
                return $this_year + 1;
            }
        }
    }

    public function regularFee()
    {
        return ($this->fees()->where('year', '>=', date('Y'))->first() != null);
    }

    public function hasRole($roles)
    {
        if (is_array($roles) == false) {
            $roles = [$roles];
        }

        foreach($this->roles as $user_role) {
            foreach($roles as $search_role) {
                if ($user_role->name == $search_role) {
                    return true;
                }
            }
        }

        return false;
    }

    public static function types()
    {
        return [
            (object) [
                'identifier' => 'regular',
                'label' => 'Ordinario'
            ],
            (object) [
                'identifier' => 'association',
                'label' => 'Associazione'
            ],
        ];
    }

    public static function statuses()
    {
        return [
            (object) [
                'identifier' => 'pending',
                'label' => 'In Attesa'
            ],
            (object) [
                'identifier' => 'active',
                'label' => 'Attivo'
            ],
            (object) [
                'identifier' => 'suspended',
                'label' => 'Sospeso'
            ],
            (object) [
                'identifier' => 'expelled',
                'label' => 'Espulso'
            ],
            (object) [
                'identifier' => 'dropped',
                'label' => 'Scaduto'
            ],
        ];
    }

    public function sendMail($class)
    {
        $user = $this;

        try {
            $custom = $user->custom_email;
            if (!empty($custom)) {
                Mail::to($user->email)->cc($custom)->send(new $class($user));
            }
            else {
                Mail::to($user->email)->send(new $class($user));
            }
        }
        catch(\Exception $e) {
            Log::error('Impossibile inoltrare mail di notifica a utente ' . $user->id . ': ' . $e->getMessage());
        }
    }

    public function getConfig($name)
    {
        $c = $this->configs()->where('name', $name)->first();
        if (is_null($c))
            return null;
        else
            return $c->value;
    }

    public function setConfig($name, $value)
    {
        $c = $this->configs()->where('name', $name)->first();
        if (is_null($c)) {
            $c = new Config();
            $c->name = $name;
            $c->subject_id = $this->id;
            $c->subject_type = 'App\User';
        }

        $c->value = $value;
        $c->save();
    }

    /******************************************************* CanResetPassword */

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));

        $custom = $this->custom_email;
        if (!empty($custom)) {
            $real_email = $this->email;
            $this->email = $custom;
            $this->notify(new ResetPasswordNotification($token));
            $this->email = $real_email;
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

use Auth;
use Hash;
use Log;

use App\Section;
use App\User;
use App\Config;

class UserController extends EditController
{
    public function __construct()
    {
        parent::init([
            'classname' => 'App\User',
            'view_folder' => 'user'
        ]);
    }

    protected function query($query, $id = null)
    {
        if (is_null($id)) {
            $query->with('section');
        }

        return $query;
    }

    protected function requestToObject($request, $object)
    {
        $fields = ['name', 'surname', 'email', 'phone', 'website', 'taxcode', 'birth_place', 'birth_prov', 'birth_date', 'address_street', 'address_place', 'address_zip', 'address_prov', 'shipping_name', 'shipping_street', 'shipping_place', 'shipping_zip', 'shipping_prov', 'size'];
        $object = $this->fitObject($object, $fields, $request);

        $object->volunteer = $request->has('volunteer');
        $object->section_id = $request->input('section_id', 0);

        if ($request->user()->hasRole('admin')) {
            $fields = ['username', 'type', 'status', 'notes', 'request_at', 'approved_at', 'expelled_at'];
            $object = $this->fitObject($object, $fields, $request);

            $roles = $request->input('roles', []);
            $object->roles()->sync($roles);
        }

        if (empty($object->notes)) {
            $object->notes = '';
        }

        if (Config::getConfig('custom_email_aliases') == '1') {
            $email_type = $request->input('email_behaviour', null);
            if (!is_null($email_type)) {
                if ($email_type == 'alias') {
                    $object->setConfig('email_behaviour', 'alias');
                }
                else {
                    $object->setConfig('email_behaviour', 'inbox');
                    $new_email_password = $request->input('email_password', null);
                    if (!empty($new_email_password)) {
                        Log::debug('Cambiata password email utente ' . $object->username);
                        $object->setConfig('email_password', mailPasswordHash($new_email_password));
                    }
                }
            }
        }

        $password = $request->input('password');
        if (!empty($password)) {
            $object->password = Hash::make($password);
        }
        else {
            if ($object->exists == false) {
                $object->password = Hash::make(str_random(10));
            }
        }

        return $object;
    }

    protected function defaultValidations($object)
    {
        $ret = [
            'name' => 'required|max:255',
            'surname' => 'required|max:255',
            'email' => 'required|email|max:255',
            'address_street' => 'required|max:255',
            'address_place' => 'required|max:255',
            'address_zip' => 'required|max:255',
            'address_prov' => 'required|max:2',
        ];

        if (Auth::user()->hasRole('admin')) {
            if (is_null($object)) {
                $ret['username'] = 'required|unique:users|max:255';
            }
            else {
                $ret['username'] = [
                    'required',
                    Rule::unique('users')->ignore($object->id),
                ];
            }

            $ret = array_merge($ret, [
                'type' => 'required|in:regular,association',
                'taxcode' => 'required|max:255',
                'birth_place' => 'required|max:255',
                'birth_prov' => 'required|max:2',
                'birth_date' => 'required|max:255',
            ]);
        }

        return $ret;
    }

    protected function defaultSortingColumn()
    {
        return 'surname';
    }

    public function approve(Request $request)
    {
        $this->checkAuth();
        $approved = $request->input('approved', []);
        User::where('status', 'pending')->whereIn('id', $approved)->update(['status' => 'active', 'approved_at' => date('Y-m-d')]);
        return redirect()->route('user.index');
    }

    public function bypass(Request $request, $id)
    {
        if ($request->user()->hasRole('admin')) {
            Auth::logout();
            Auth::loginUsingId($id);
        }

        return redirect('/');
    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form method="POST" action="{{ route('user.update', $object->id) }}">
                @method('PUT')
                @csrf

                @include('user.form', ['object' => $object])

                <hr>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Salva</button>
                    </div>
                </div>
            </form>

            @if($currentuser->hasRole('admin') && $object->status == 'pending')
                <form method="POST" action="{{ route('user.destroy', $object->id) }}">
                    @method('DELETE')
                    @csrf

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-danger">Elimina</button>
                        </div>
                    </div>
                </form>
            @endif
        </div>
        <div class="col-md-3 offset-md-1">
            <h5>Quote Versate</h5>

            @if($object->fees()->count() == 0)
                <div class="alert alert-danger">
                    Nessuna quota versata sinora.
                </div>
            @else
                <ul class="list-group">
                    @foreach($object->fees()->orderBy('year', 'desc')->get() as $fee)
                        <li class="list-group-item">
                            {{ $fee->year }}

                            @if($fee->receipt())
                                <span class="float-right"><a href="{{ $fee->receipt()->link }}">Ricevuta {{ $fee->receipt()->number }}</a></span>
                            @endif
                        </li>
                    @endforeach
                </ul>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @can('create', App\User::class)
        <div class="row">
            <div class="col-md-12">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createUser">Registra Nuovo</button>
                <div class="modal fade" id="createUser" tabindex="-1" role="dialog">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Registra Socio</h5>
                                <button type="button" class="close" data-dismiss="modal">
                                    <span>&times;</span>
                                </button>
                            </div>
                            <form method="POST" action="{{ route('user.store') }}">
                                @csrf
                                <div class="modal-body">
                                    @include('user.form', ['object' => null])
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                                    <button type="submit" class="btn btn-primary">Salva</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <button class="btn btn-default show-all" data-target=".table">Mostra Tutti</button>
            </div>
        </div>
    @endif

    <div class="row mt-3">
        <div class="col-md-12">
            <div class="alert alert-info">
                Ci sono attualmente {{ App\User::where('status', 'active')->where('type', 'regular')->count() }} persone e {{ App\User::where('status', 'active')->where('type', 'association')->count() }} associazioni iscritte.
            </div>
        </div>
    </div>

    @if($currentuser->hasRole('admin'))
        @if(App\User::where('status', 'pending')->orderBy('surname')->count() > 0)
            <div class="row mt-3">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">Soci in Attesa di Approvazione</div>

                        <div class="card-body">
                            <form method="POST" action="{{ route('user.approve') }}">
                                @csrf

                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Cognome</th>
                                            <th>Nome</th>
                                            <th>Nickname</th>
                                            <th>Sezione</th>
                                            <th>Domanda</th>
                                            <th>Quota Pagata</th>
                                            <th>Modifica</th>
                                            <th>Approva</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach(App\User::where('status', 'pending')->orderBy('surname')->get() as $user)
                                            <tr>
                                                <td>{{ $user->name }}</td>
                                                <td>{{ $user->surname }}</td>
                                                <td>{{ $user->username }}</td>
                                                <td>{{ $user->section ? $user->section->city : '' }}</td>
                                                <td>{{ $user->request_at }}</td>
                                                <td>{{ $user->fees()->count() > 0 ? 'SI' : 'NO' }}</td>
                                                <td><a href="{{ route('user.edit', $user->id) }}"><span class="oi oi-pencil"></span></a></td>
                                                <td><input type="checkbox" name="approved[]" value="{{ $user->id }}"></td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>

                                <div class="form-group row">
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Salva</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endif
    @endif

    <div class="row mt-3">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Cognome</th>
                        <th>Nome</th>
                        <th>Nickname</th>
                        <th>Sezione</th>

                        @if($currentuser->hasRole('admin'))
                            <th>Quota</th>
                            <th>Stato</th>
                            <th>Modifica</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    @foreach($objects as $user)
                        <tr class="{{ in_array($user->status, ['expelled', 'dropped']) ? 'hidden' : '' }}">
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->surname }}</td>
                            <td>{{ $user->expelled_at ? 'ESPULSO' : $user->username }}</td>
                            <td>{{ $user->section ? $user->section->city : '' }}</td>

                            @if($currentuser->hasRole('admin'))
                                <td>{{ $user->fees()->max('year') }}</td>
                                <td>{{ $user->human_status }}</td>
                                <td><a href="{{ route('user.edit', $user->id) }}"><span class="oi oi-pencil"></span></a></td>
                            @endif
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/user/select.blade.php
<?php

if (!isset($name))
    $name = 'user[]';

if (!isset($select))
    $select = 0;

if (!isset($status)) {
    $status = array_map(function($n) {
        return $n->identifier;
    }, App\User::statuses());
}
else if (!is_array($status)) {
    $status = [$status];
}

?>

<select class="form-control" name="{{ $name }}" autocomplete="off">
    <option value="0" {{ $select == 0 ? 'selected' : '0' }}>Nessuno</option>
    @foreach(App\User::whereIn('status', $status)->orderBy('surname', 'asc')->get() as $user)
        <option value="{{ $user->id }}" {{ $select == $user->id ? 'selected' : '' }}>{{ $user->printable_name }} ({{ $user->username }})</option>
    @endforeach
</select>